# Created separate chart as was not able to upgrade this as part of the cluster-infra
# bundle. Since 
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJkcGJzdyIsInBhc3N3b3JkIjoiSmF2YV9zY3JpcHQxIiwiZW1haWwiOiJkcGJzb2Z0d2FyZUBnbWFpbC5jb20iLCJhdXRoIjoiWkhCaWMzYzZTbUYyWVY5elkzSnBjSFF4In19fQ==
