# This chart creates the POD and cluster ip service in the name space of a specific environment
# (e.g. picb;pg-dev namespace, picblog-test namespace, or  picblog-prod namespace). 
# The extname.yaml (created in pic-infra chart), creates an externalName service, which functions 
# as a proxy service with the same name as the cluster ip service within the default namespace. 
# When ingress looks up cluster ip name, it will find the
# proxy service in the default namespace. The proxy service within in the default namespace 
# will route (or map) the traffic to cluster-ip-service within the "env" namespace (dev, test, or prod).
apiVersion: apps/v1
kind: Deployment
metadata:
  name: picblog-{{ .Values.env }}-depl 
  namespace: pic-{{ .Values.env }}
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: picblog
  template: 
    metadata: 
      labels:
        app:  picblog
        type: nextjs
        tier: frontend
    spec:
      containers:
        - name: picblog
          image: dpbsw/picblog-{{ .Values.env }}:v{{ .Chart.AppVersion }}
          env: 
            - name: NODE_ENV
              value: {{ .Values.nodeEnv | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy}}
      imagePullSecrets:
        - name: regcred       