apiVersion:  networking.k8s.io/v1
kind: Ingress
metadata:
  # name: ingress-svc /* used ingress-resource as this is name used on GKE */
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: {{ .Values.env }}.pitchinclub.com
      http:
        paths: 
        - path: /?(.*)
          pathType: Prefix
          backend:
            service:
              name: picblog-clusterip-svc
              port:
                number: 3000
    