apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJkcGJzdyIsInBhc3N3b3JkIjoiSmF2YV9zY3JpcHQxIiwiZW1haWwiOiJkcGJzb2Z0d2FyZUBnbWFpbC5jb20iLCJhdXRoIjoiWkhCaWMzYzZTbUYyWVY5elkzSnBjSFF4In19fQ==
kind: Secret
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:.dockerconfigjson: {}
      f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2021-02-24T18:34:49Z"
  name: regcred
  namespace: default
  resourceVersion: "1388791"
  selfLink: /api/v1/namespaces/default/secrets/regcred
type: kubernetes.io/dockerconfigjson
