# This service creates an externalName service, which functions as
# a proxy service with the same name as the cluster ip service but within the default namespace.
# The pic chart creates the POD and the cluster ip service in the name space for the specific environment
# (e.g. dev namespace, test namespace, or  prod namespace). 
# When ingress looks up cluster ip name, it will find the
# proxy service in the default namespace. The proxy service within in the default namespace 
# will route (or map) the traffic to cluster-ip-service within the "env" namespace (dev, test, or prod).
apiVersion: v1
kind: Service
metadata:
  name: picblog-{{ .Values.env }}-clusterip-svc
spec:
  type: ExternalName
  externalName: picblog-{{ .Values.env }}-clusterip-svc.pic-{{ .Values.env }}.svc.cluster.local

# apiVersion: v1
# kind: Service
# metadata:
#   name: picblog-{{ .Values.env }}-clusterip-svc
# spec:
#   type: ExternalName
#   externalName: picblog-{{ .Values.env }}-clusterip-svc.pic-{{ .Values.env }}.svc.cluster.local


# Note: externalName uses the following format
#  cluster ip name             | namespace | svc.cluster.local
#  picblog-<env>-clusterip-svc | pic-dev   | svc.cluster.local